#!/bin/sh /etc/rc.common

# Copyright (c) 2006, Roberto Riggio
#
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions    
# are met:
# 
#   - Redistributions of source code must retain the above copyright 
#     notice, this list of conditions and the following disclaimer.
#   - Redistributions in binary form must reproduce the above copyright 
#     notice, this list of conditions and the following disclaimer in 
#     the documentation and/or other materials provided with the 
#     distribution.
#   - Neither the name of the CREATE-NET nor the names of its 
#     contributors may be used to endorse or promote products derived 
#     from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

START=98

. /lib/functions.sh

start() {                                                           
                                                                    
        while [ 1 ]; do                                         
		sleep 5                                                     
		UP=$(uci -p /var/state/ get network.mesh.up)                   
		[ "${UP}x" == "1x" ] && {
			IPADRR=$(uci -p /var/state/ get network.mesh.ipaddr)    
			SSID24=$(uci -p /var/state/ get wireless.hotspot24.ssid)   
			SSID5=$(uci -p /var/state/ get wireless.hotspot5.ssid)
			NEW_SSID="WING-$IPADRR"                                    
			[ "${NEW_SSID}x" != "${SSID24}x" ] && {                                
				uci_set wireless hotspot24 ssid "$NEW_SSID"            
				uci_commit wireless                                  
			}                                                           
			[ "${NEW_SSID}x" != "${SSID5}x" ] && {                        
				uci_set wireless hotspot5 ssid "$NEW_SSID"          
				uci_commit wireless                           
			}
			break
		}
        done
         
}

